
export const MIN_DATE = new Date("1940-01-01");

export const TABLE_ACTIONS = {
    ADD: 'ADD',
    VIEW: 'VIEW',
    EDIT: 'EDIT',
    ACTIVATE: 'ACTIVATE',
    INACTIVATE: 'INACTIVATE',
    PUTDOWN: 'PUTDOWN',
    ADDLICENCE: 'ADDLICENCE',
    RENEWLICENCE: 'RENEWLICENCE',
    PUTDOWNLICENCE: 'PUTDOWNLICENCE',
    ADDFAMILY: 'ADDFAMILY',
    REENTRY: 'REENTRY',
    CHANGEPOSITION: 'CHANGEPOSITION'
}

export const FORM_ACTIONS = {
    CLOSE: 'CLOSE',
    CONFIRM: 'CONFIRM'
}

export const MODAL_FORM = {
    DYNAMICMODAL: 'DYNAMICMODAL',
    EMPLOYEEMODAL: 'EMPLOYEEMODAL'
}